### ISSUE TITLE
Recursive cleaning does not work

### ISSUE THREAD

**Issue by steache** [alexandre-abrioux/gulp-rev-dist-clean#1]
Hello,
I was trying to use your package but I've encountered weird behaviour.
We have **rev-manifest.json** with only around ~600 files, but they are in few nested folders.
For example (js, css, img (flags, icons, avatars), fonts (fontwesome, anotherfonts)).

After adding `console.log(file.path)` to line https://github.com/alexandre-abrioux/gulp-rev-dist-clean/blob/master/index.js#L27 before the condition it prints out:

```
build\css
build\fonts
build\img
build\js
build\rev-manifest.json
build\css\base
build\css\bootstrap
build\css\bootstrap-multiselect-9fbf7bf47b.css
build\css\calendar
build\css\flot
build\css\jquery.linkselect-5f50594e27.css
build\css\pages
build\css\qtip
build\css\slickgrid
build\css\spam-dash-62c330442f.css
build\css\stats-admin-a36841a59c.css
build\css\style-c60c061139.css
```

It does not even try to walk through js or other folders.
I'm using version **1.0.4**

It's being called from gulpfile like this:
```
gulp.task('rev-dist-clean', function(){
	gulp.src(['build/**/*'], {read: false})
		.pipe(revDistClean('build/rev-manifest.json'))
});
```

Am I doing something wrong? :)
Thanks !

After another debug I've discovered, that settings (https://github.com/rvagg/through2/blob/master/through2.js#L88) from 16 to 5000 does the trick.

So what now. :)

This does the trick. I've found it after looking at different gulp packages like (https://github.com/galkinrost/gulp-rev-css-url/blob/master/index.js#L40)

![2017-12-07_1040](https://user-images.githubusercontent.com/34166829/33708579-2558244a-db3b-11e7-8074-b2a5293551a5.png)

**Comment by alexandre-abrioux** [comment]
Hi @steache 
I forgot about this repo and haven't checked it in months now: just saw your feedback yesterday, sorry about that!

Thank you for the debugging, that was very helpful.
I created a [new release](https://github.com/alexandre-abrioux/gulp-rev-dist-clean/releases/tag/v2.0.0) with the help you gave me.
The fix was brought with https://github.com/alexandre-abrioux/gulp-rev-dist-clean/commit/594bb0fb3b8a477a35c1aa1ac8e264fa2cab7976.

There was indeed an issue when no further gulp `.pipe()` processing is done after the `revDistClean()` plugin. The cause is well explained here: https://github.com/rvagg/through2/issues/32#issuecomment-62645342

We actually need the code `cb(null, file)` if we desire to further process the files after `revDistClean()`. By only using `cb()` in the `through.obj()` "transform function" we would always produce an empty stream as an output that wouldn't be useful for any further processing.

But in your example, as in the majority of the cases, the `revDistClean()` is the last plugging of the involved gulp task, hence the need to call `cb()`without any argument for each and every file.

Therefore I added a new option `emitChunks` that enables the control of this behavior. The default value - `false` - assumes no further processing is required and does not emit any chunk. If set to `true` chunks are emitted, as it was the case in `v1.0.4`.

I also added some unit tests and another option `keepManifestFile` (set to `true` by default), a change that breaks backward compatibility. Because of that you will need to update your `package.json` with the new major version: `v2.0.0`. This should work for you without changing any conf :)

Cheers!
